Issue 5298: Use Bookkeeper client config to mitigate FrameTooLongException
pravega/pravega pull request #5299
Opened 2020-11-04 17:55 UTC by RaulGracia

**Change log description**  
(2-3 concise points about the changes in this PR. When committing this PR, the committer is expected to copy the content of this section to the merge description box)

**Purpose of the change**  
Fixes #5298.

**What the code does**  
(Detailed description of the code changes)

**How to verify it**  
(Optional: steps to verify that the changes are effective)

2020-11-11 16:44 UTC, andreipaduroiu approved these changes

2020-11-11 16:46 UTC, andreipaduroiu commented on segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java
> +                .setNettyMaxFrameSizeBytes(BookKeeperConfig.MAX_APPEND_LENGTH)
This value is smaller than the actual frame length. The BK Client will wrap our data in an envelope which will increase this size. If this value is passed per-se to Netty, I don't understand how the system could still work. That's unless there's other code in the BK client to increase this value to account for the extra envelope size. 

Would you mind checking in the BK client code to see how this is handled?

2020-11-11 16:47 UTC, andreipaduroiu requested changes
See above.

2020-11-24 14:23 UTC, RaulGracia commented
Closing, as this mechanism only involves the client decoding, not the encoding. This means that the server is exposed anyway to large messages from the Bookkeeper clients (I could reproduce the `FrameTooLongException` despite this setting).

2020-11-24 14:23 UTC, closed without merging