Issue 5308: Make max read length configurable in PravegaRequestProcessor
pravega/pravega pull request #5370
Opened 2020-11-24 16:25 UTC by RaulGracia

**Change log description**  
Added a parameter (`pravegaservice.request.read.length.max`) to configure the max size of reads that the `PravegaRequestProcessor` issues to the cache. Also, this PR aligns the default values of `pravegaservice.request.read.length.max` and `readindex.storageRead.alignment` according to the max read length that clients can issue (i.e., 10MB).

**Purpose of the change**  
Fixes #5308.

**What the code does**  
To improve the performance of historical reads when just few segments are available in parallel, we need to issue larger reads to LTS. However, one hardcoded variable (`MAX_READ_SIZE`, set to 2MB) in `PravegaRequestProcessor` was preventing large reads from clients (up to 10MB) to take effect. This PR basically replaces such a hardcoded variable by a configurable parameter.

In addition, to better exploit large client reads issues to LTS, we aligned the values of `pravegaservice.request.read.length.max` (reads from `PravegaRequestProcessor` to the cache) and `readindex.storageRead.alignment` (prefetch from LTS to cache) according to the max read size of clients (10MB at the moment, as defined in `SegmentInputStreamImpl`).

**How to verify it**  
All tests should be working as before with the new configuration parameter.

2020-11-24 16:35 UTC, andreipaduroiu requested changes

2020-11-24 16:35 UTC, andreipaduroiu commented on segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java
> +                                                      this.serviceConfig.isReplyWithStackTraceOnError(),
Any chance we could do something to this constructor? It's getting out of hands. Could we add a `@Builder` tag to it?

If we do add a `@Builder`, then we could potentially get rid of the other 1-2 constructors next to it and supply defaults via the builder object.

Not really related to this PR, but every time I had to modify this area of the code I found myself having to modify a good number of other files too.

2020-11-24 16:35 UTC, andreipaduroiu commented on segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaConnectionListener.java
> +                new PassingTokenVerifier(), null, null, true, 10 * 1024 * 1024, tokenExpiryExecutor);
Such as this constructor. That value could be a nice default in a builder, along with all the nulls and no-op classes.

2020-11-24 16:35 UTC, andreipaduroiu commented on segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaConnectionListener.java
> +        this.maxReadLength = maxReadLength;
Please add a `Preconditions.checkArgument` to validate that this is at least X KB. (X == 10?).

2020-11-24 16:35 UTC, andreipaduroiu commented on segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
> +                            DelegationTokenVerifier tokenVerifier, boolean replyWithStackTraceOnError, int maxReadLength) {
Another candidate for `@Builder` :)

2020-11-24 16:35 UTC, andreipaduroiu commented on segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
> +        this.maxReadLength = maxReadLength;
Validate.

2020-11-24 16:35 UTC, andreipaduroiu commented on segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java
> +        final int readSize = min(maxReadLength, max(TYPE_PLUS_LENGTH_SIZE, readSegment.getSuggestedLength()));
`MathHelpers.minMax`

2020-11-24 16:35 UTC, andreipaduroiu commented on segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorAuthFailedTest.java
> +                }, false, 10 * 1024 * 1024);
why not use the constant here?

2020-11-24 16:35 UTC, andreipaduroiu commented on segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java
> +        this.requestProcessorMaxReadLength = properties.getInt(REQUEST_PROCESSOR_MAX_READ_LENGTH);
Validate that it is positive. And optionally greater than some min value. Let's make it consistent with PravegaRequestProcessor/Listener

2020-11-25 18:05 UTC, andreipaduroiu commented
I have certain reservations when it comes to increasing these values ten-fold. I like it that we made them configurable, but I believe that we should keep the defaults as they are. We can set them to higher values at deployment time, and if this proves not to introduce instability in the system, we can choose to update the defaults as well.

2021-06-11 09:42 UTC, RaulGracia commented
Closing this one. If needed, I will raise it again.

2021-06-11 09:42 UTC, closed without merging