Issue : Fix EventProcessor integration test.
pravega/pravega pull request #5399
Opened 2020-12-03 10:29 UTC by shrids

Fix missing resource closure.

**Change log description**  
(2-3 concise points about the changes in this PR. When committing this PR, the committer is expected to copy the content of this section to the merge description box)

**Purpose of the change**  
(_e.g._, Fixes #666, Closes #1234)

**What the code does**  
(Detailed description of the code changes)

**How to verify it**  
(Optional: steps to verify that the changes are effective)

2020-12-03 16:37 UTC, shiveshr approved these changes

2020-12-04 00:17 UTC, andreipaduroiu commented on build.gradle
> +        beforeTest { descriptor ->
Why did you do this just for integration tests? We should have consistency across our tests.

2020-12-04 00:36 UTC, andreipaduroiu requested changes
Please hold off on this change. I am working on #5401 which also covers this test.

2020-12-08 04:51 UTC, closed without merging

2020-12-08 04:59 UTC, shrids commented
Closing this PR as it is superseded by #5402