Issue 5501: Add new command to parse RG stream file
pravega/pravega pull request #5502
Opened 2021-01-10 22:46 UTC by Tristan1900

**Change log description**  
Adds a new command to CLI to parse the ReaderGroup stream file.

**Purpose of the change**  
Fix 5501

**What the code does**  
Read stream file header first (4 bytes type + 4 bytes length) and then read the content based on length. Use Java client deserializer to deserialize the content and output to a file.

**How to verify it**  
Manually tested

2021-02-23 04:00 UTC, shrids approved these changes
LGTM...

2021-02-26 21:46 UTC, Tristan1900 commented
Hey @RaulGracia , could you take a look at this PR and see if it looks good to you? I have tested manually and used it couple of times for debugging so it should work. 
Thanks!

2021-03-15 18:31 UTC, RaulGracia commented
@Tristan1900 looks like there is an issue with code coverage, once you make it happy we can resume with this PR.

2021-03-15 18:32 UTC, RaulGracia commented on cli/admin/src/test/java/io/pravega/cli/admin/debug/ReaderGroupStreamFileParsingCommandTest.java
> +    public void testPasswordFileCreatorCommand() throws Exception {
Looks like a bad name for a test.

2021-03-15 18:34 UTC, RaulGracia commented on cli/admin/src/test/java/io/pravega/cli/admin/debug/ReaderGroupStreamFileParsingCommandTest.java
> +        byte[] bytes = {0, 0, 0, 0, 0, 0, 0, 0};
Is there a way to test with a more realistic content that actually has some info about a reader group?

2021-03-15 18:36 UTC, RaulGracia commented on cli/admin/src/main/java/io/pravega/cli/admin/debug/ReaderGroupStreamFileParsingCommand.java
> + * It parses the serialized ReaderGroup Stream file to a human readable file.
Please, rephrase this so it is clearer what this command does and why it is useful for. Perhaps mentioning an example or scenario where this command is expected to be used could help.

2021-03-15 18:37 UTC, RaulGracia commented on cli/admin/src/main/java/io/pravega/cli/admin/debug/ReaderGroupStreamFileParsingCommand.java
> + * The command takes input stream file and output stream file as argument.
How is the user supposed to the this "input file"?

2021-05-04 17:18 UTC, andreipaduroiu requested changes

2021-05-04 17:18 UTC, andreipaduroiu commented on cli/admin/src/main/java/io/pravega/cli/admin/debug/ReaderGroupStreamFileParsingCommand.java
> +            String outputFileName = getOutputStreamFilename(getCommandArgs().getArgs());
This should be rewritten to make use of either RevisionedStreamClient/ByteStreamClient or the Admin Gateway (raw read of the segment file). 

How is this file supposed to get to your local filesystem in the first place? How do you download it from Pravega?

2021-07-08 14:54 UTC, andreipaduroiu commented
@Tristan1900 What is the status of this PR? Are we still pursuing it?

2021-10-01 20:46 UTC, closed without merging