Restoring empty segments.
pravega/pravega pull request #5528
Opened 2021-01-15 07:19 UTC by ManishKumarKeshri

Signed-off-by: ManishKumarKeshri <manish.keshri562@gmail.com>

**Change log description**  
During update attributes, if it's found that one segment exists in the old metadata segment, but doesn't exist in the new metadata segment (one created after recovery), then register the segment using the details in the old container metadata segment and update its attrubutes.

**Purpose of the change**  
Fixes #5527 

**What the code does**  
Objective is to register the segments which don't exist in the LTS, but are present in container metadata segment. 

**How to verify it**  
Build shall pass.

2021-01-15 21:24 UTC, sachin-j-joshi approved these changes
LGTM

2021-01-15 22:18 UTC, ManishKumarKeshri commented
One if the tests `testDurableDataLogFailRecoveryWatermarking ` is flaky. Looking into it.

2021-01-15 22:22 UTC, sachin-j-joshi requested changes
ok

2021-05-25 08:29 UTC, ManishKumarKeshri commented
> ok

flakiness will be resolved in this PR: https://github.com/pravega/pravega/pull/5816

2021-05-25 14:43 UTC, andreipaduroiu requested changes

2021-05-25 20:49 UTC, ManishKumarKeshri commented on segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java
> +     *      * and takes one of the following actions:
That was supposed to be deleted. Fixed it.

2021-05-25 20:50 UTC, ManishKumarKeshri commented on segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java
> +     * Registers a segment in the {@link MetadataStore} of the given {@link DebugStreamSegmentContainer} instance using the
Using just this one.

2021-05-25 20:50 UTC, ManishKumarKeshri commented on segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java
> +                .thenAccept(x -> container.updateAttributes(segment.getName(), attributeUpdates, timeout));
Ok! Done.

2021-05-25 22:29 UTC, andreipaduroiu approved these changes

2021-05-28 10:14 UTC, ManishKumarKeshri commented
!Please do not merge. The added test `testRegisterSegmentAndUpdateAttributes` appears to be flaky. The problem is:
Though I create a segment with deleted = false [here](https://github.com/pravega/pravega/blob/1280b96fb0962c98f61b5d75b21101d5a3a8af58/segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java#L521), but finally when it tries to get the segment info [here](https://github.com/pravega/pravega/blob/1280b96fb0962c98f61b5d75b21101d5a3a8af58/segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java#L508), sm.isDeleted is returned as true.
```
    private CompletableFuture<SegmentProperties> getSegmentSnapshot(long segmentId, String segmentName) {
        SegmentMetadata sm = this.connector.containerMetadata.getStreamSegmentMetadata(segmentId);
        if (sm == null || sm.isDeleted() || sm.isMerged()) {
            return Futures.failedFuture(new StreamSegmentNotExistsException(segmentName));
        } else {
            return CompletableFuture.completedFuture(sm.getSnapshot());
        }
    } 
```
while creation
```
Name = segment--920768406, StartOffset = 0, Length = 3076, Storage Length = 0, Sealed = false, Deleted = false, Sealed in Storage = false, Deleted in Storage = false
```
while retrieval
```
Id = 3, Start = 0, Length = 3076, StorageLength = 3076, Sealed(M/S) = false/false, Deleted = true, Name = segment--920768406`
```

2021-05-28 10:14 UTC, RaulGracia requested changes
Blocking for safety.

2021-06-01 18:37 UTC, RaulGracia commented
After a discussion with @andreipaduroiu, it looks like we may not need this one in the short term. Closing it.

2021-06-01 18:37 UTC, closed without merging