Issue 5618: Add a test to confirm that a stream can be deleted when transactions are open
pravega/pravega pull request #5619
Opened 2021-02-02 19:52 UTC by claudiofahey

**Change log description**  
Add a test to confirm that a stream can be deleted when transactions are open.

**Purpose of the change**  
Closes #5618.

**What the code does**  
This creates a stream and writes transactions in various states (opened, flushed, committed). It then ensures that it can seal and delete the stream.

**How to verify it**  
Run `./gradlew test` or use Intellij to run test/integration/src/test/java/io/pravega/test/integration/DeleteStreamWithOpenTransactionTest.java.

2021-03-23 09:07 UTC, RaulGracia reviewed
Looks good, but wondering if you could add this test case in the `TransactionTest.java` suite in the integration package. It looks like there we are currently concentrating most of the transaction-related integration tests.

2021-03-25 17:41 UTC, RaulGracia commented on test/integration/src/test/java/io/pravega/test/integration/TransactionTest.java
> +    @Test(timeout = 30000)
Please, add one blank line to separate tests.

2021-03-25 17:56 UTC, RaulGracia requested changes
Checkstyle is failing.

2021-03-26 01:36 UTC, shrids approved these changes

2021-03-26 08:33 UTC, RaulGracia approved these changes

2021-03-26 08:51 UTC, merged