SLTS - cherry picks for r0.9.1
pravega/pravega pull request #5782
Opened 2021-02-23 19:11 UTC by sachin-j-joshi

**Change log description**  
SLTS - cherry picks for r9.1

**Purpose of the change**  
Fixes #5780

**What the code does**  
Cherry-picks following changes

**How to verify it**  
Tests should pass

2021-03-11 22:59 UTC, sachin-j-joshi commented
- [ ] System tests passed with NFS with append.

2021-03-12 17:15 UTC, andreipaduroiu approved these changes

2021-03-12 18:31 UTC, andreipaduroiu requested changes
holding off for now.

2021-03-16 17:38 UTC, andreipaduroiu approved these changes

2021-03-19 22:39 UTC, merged