Issue 5393: Cherrypick fix to r0.9
pravega/pravega pull request #5822
Opened 2021-03-09 04:51 UTC by pbelgundi

Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
Segment Helper and Flow Handler APIs get invoked multiple times during a single Controller operation, esp. during transaction processing.
Info Logs explaining the details of each operation cause too many logs to be written and sometimes cause Controller to run our of disk space.

**Purpose of the change**  
Fixes #5393

**What the code does**  
Changed the log level, from "INFO" to "DEBUG", for low-level operations in Segment Helper and Flow Handler, since these logs are only needed for debugging.
Changed `logback.xml` to include a new _SizeAndTimeBasedRollingPolicy_ for logs with a cap on the size of Controller logs. That way we can be sure that the disk space occupied by Controller logs never exceeds a certain limit.

**How to verify it**  
All tests should pass.
Size of logs on Controller pod should not exceed the value specified against totalSizeCap in logback.xml

2021-03-09 12:07 UTC, kotlasaicharanreddy approved these changes

2021-03-09 21:31 UTC, sachin-j-joshi requested changes
Let's wait until we have cherry-picked PRs for outstanding blocking issues first.

2021-03-10 04:44 UTC, shiveshr commented
@andreipaduroiu there was a controller pod eviction due to excessive logging esp with transaction workloads. this fixes it in two ways - 1. log rotation based on size 2. reduces some of the noisy logs. This will make sure controller pods are not evicted due to logs filling up the disk.

2021-03-10 04:51 UTC, pbelgundi commented
> @pbelgundi Please explain why this is needed in 0.9.1. Thanks!
> 
> cc @sachin-j-joshi

We recently noticed that on some Pravega environments, Controller pods went out of disk space due to excessive logging, especially during transactions and hence Controller kept getting restarted. This PR fixes that. It would help to have this in 0.9.1

2021-03-18 19:38 UTC, sachin-j-joshi requested changes
Looks like codecov is not happy.

2021-03-19 21:31 UTC, sachin-j-joshi reviewed
Code coverage issue is resolved now.

2021-03-19 21:31 UTC, sachin-j-joshi commented
@shiveshr Is this good to go now ? If yes please approve it.
Thanks

2021-03-22 04:28 UTC, shiveshr approved these changes

2021-03-22 04:56 UTC, merged