Open visibility of AsyncBaseChunkStorage.OperationContext
pravega/pravega pull request #5829
Opened 2021-03-10 15:55 UTC by diegosalvi

**Change log description**  
Visibility change of AsyncBaseChunkStorage.OperationContext to protected

**Purpose of the change**  
Be able to implement AsyncBaseChunkStorage abstraction methods for external plugins

**What the code does**  
Just a visibility change of AsyncBaseChunkStorage.OperationContext from default to protected

**How to verify it**  
Implement AsyncBaseChunkStorage outside io.pravega.segmentstore.storage.chunklayer package

2021-03-10 16:01 UTC, eolivelli commented
@diegosalvi  I believe you have to "sign" your commits in order to make DCO checker happy.

Also please create an issue, in Pravega we are using github issues in order to create the release notes

2021-03-10 16:02 UTC, eolivelli requested changes

2021-03-10 16:02 UTC, eolivelli commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java
> +    protected static class OperationContext {
can we add a comment that explains that this class is intended to be used by subclasses and how ?

2021-03-10 17:34 UTC, andreipaduroiu requested changes
@diegosalvi Thank you for your contribution!

I see this is your first PR on Pravega. As you probably already observed, we have some checks enabled on our repository that must pass before merging.

Please refer to our contribution guidelines (https://github.com/pravega/pravega/wiki/Contributing#issuesandprs), which explains how to create PRs (and associated issues) and how to sign your commits.

2021-03-14 14:34 UTC, fpj commented
Is there an issue associated to this PR?

2021-03-15 20:02 UTC, sachin-j-joshi commented
Created an Issue.  @diegosalvi  Please use this in commit description and PR comments.
https://github.com/pravega/pravega/issues/5847

2021-03-18 08:08 UTC, diegosalvi commented
Changed commit descrition to match issue #5847 and signed off.

2021-03-22 14:04 UTC, diegosalvi commented
Hi, I think I've added all requested changes, I'm missing anything?

2021-03-25 18:28 UTC, sachin-j-joshi approved these changes
LGTM

2021-03-25 18:55 UTC, eolivelli approved these changes
LGTM

2021-03-31 14:27 UTC, sachin-j-joshi commented
@andreipaduroiu are we good to go ?

2021-04-01 15:11 UTC, andreipaduroiu approved these changes
Thank you for creating an issue. In the future, please follow our contribution guidelines and pull request guidelines - in particular, how to reference issues from PRs.

I have fixed this PR for you (Title + `Fixes`). Good to go.

2021-04-01 16:08 UTC, merged