Issue 5846 exception to force segment container shutdown
pravega/pravega pull request #5910
Opened 2021-04-01 23:00 UTC by ManishKumarKeshri

**Change log description**  
Replaced `DataCorruptionException` with `ServiceHaltException` in required places.

**Purpose of the change**  
Fixes #5846 

**What the code does**  
Created a new exception `ServiceHaltException` which inherits from `StreamingException`. Made `DataCorruptionException` extend from it. Replaced `DataCorruptionException` with `ServiceHaltException` in required places.

**How to verify it**  
Build shall pass.

2021-04-14 20:50 UTC, andreipaduroiu approved these changes

2021-04-16 16:59 UTC, RaulGracia requested changes

2021-04-16 16:59 UTC, RaulGracia commented on segmentstore/server/src/main/java/io/pravega/segmentstore/server/ServiceHaltException.java
> +public class ServiceHaltException extends StreamingException {
Add comments to this Exception.

2021-04-16 16:59 UTC, RaulGracia commented on segmentstore/server/src/main/java/io/pravega/segmentstore/server/ServiceHaltException.java
> +     *
Do we need a blank comment here?

2021-04-16 16:59 UTC, RaulGracia commented on segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java
> +     *      *                          CachedStreamSegmentAppendOperation.
Remove this extra `*`.

2021-04-21 20:43 UTC, ManishKumarKeshri commented
Moved the changes to https://github.com/pravega/pravega/pull/5952.

2021-04-21 20:43 UTC, closed without merging