Issue 6112: System Test Log Bundle Format
pravega/pravega pull request #6115
Opened 2021-06-30 16:49 UTC by co-jo

**Change log description**  

* If available, the system test log collection will default to bundle the log files using `zip` instead of a compress tar.

**Purpose of the change**  

* Fixes #6112 

**What the code does**  

* By default calls `zip`.

**How to verify it**  

Run system test(s) and collect the logs using `fluentBitSetup.sh`

2021-07-07 08:46 UTC, anishakj approved these changes
LGTM

2021-07-07 09:20 UTC, RaulGracia commented
Running system tests with last commit before approving.

2021-07-07 13:52 UTC, RaulGracia requested changes
LGTM, but we need to verify that the new code gathers the logs correctly.

2021-08-31 08:23 UTC, RaulGracia approved these changes

2021-08-31 09:36 UTC, merged