Issue 611: Large Append Wirecommand
pravega/pravega pull request #6119
Opened 2021-07-02 15:18 UTC by co-jo

**Change log description**  

* Adds new WireCommand(s) and create method stubs in appropriate classes.

**Purpose of the change**  

Finishes #6116

2021-07-06 14:56 UTC, andreipaduroiu requested changes
This PR seems like it has a lot of unrelated changes into it.

Can you please update the base branch with the latest master and then rebase/remerge your PR so we don't see all this health check changes too?

2021-07-06 15:44 UTC, co-jo commented
> 
> 
> This PR seems like it has a lot of unrelated changes into it.
> 
> Can you please update the base branch with the latest master and then rebase/remerge your PR so we don't see all this health check changes too?

Yes, my mistake.

2021-07-08 19:07 UTC, tkaitchuck requested changes

2021-07-08 19:07 UTC, tkaitchuck commented on shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
> +        final String segmentName;
parentSegment?

2021-07-08 19:07 UTC, tkaitchuck commented on shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java
> +        final long requestId;
Should this contain a writerId?

2021-07-08 19:07 UTC, tkaitchuck commented on shared/protocol/src/test/java/io/pravega/shared/protocol/netty/DelegatingRequestProcessorTest.java
> +    public void testEverythingCalled() {
This doesn't actually assert anything. 
It should include an assertion that each method on the processor delegated to was invoked .

2021-07-13 16:15 UTC, andreipaduroiu approved these changes

2021-07-13 18:29 UTC, tkaitchuck approved these changes

2021-07-13 18:30 UTC, tkaitchuck reviewed
Looks good. You just need to bump the wire command version, so that later we detect if these commands are present if needed.

2021-07-13 18:30 UTC, merged

2021-07-13 18:31 UTC, andreipaduroiu commented
@tkaitchuck We've already bumped the wire command version for the 0.10 release. We'll only bump it up again if we won't be able to merge this feature before the 0.10 release cutoff.