6012 System test for Stream Tags
pravega/pravega pull request #6151
Opened 2021-07-14 13:24 UTC by shshashwat

**Change log description**  
Added a new system test for the new feature System Tags.

**Purpose of the change**  
#6012 

**What the code does**  
Create the streams
Perform tests on empty and non-empty streams
Update streams with tags
Update a stream tag and verify if it is reflected
Seal and Delete the Stream
check if list streams is updated

**How to verify it**  
All tests and system tests must pass

2021-07-20 09:17 UTC, shrids commented on test/system/src/test/java/io/pravega/test/system/StreamsAndScopesManagementTest.java
> +            assertEquals(singletonList(Stream.of(scope, stream)), newArrayList(streamManager.listStreams(scope, "t1")));
in the subsequent iterations, the streams returned by `streamManager.listStreams` should not be a singleton list, right ?

2021-07-21 11:29 UTC, shshashwat commented
System tests are in progress

2021-07-22 22:27 UTC, tkaitchuck approved these changes

2021-07-23 04:15 UTC, shrids requested changes
The changes look good. Blocking until we have a successful System test run.

2021-07-23 04:15 UTC, shrids commented on test/system/src/test/java/io/pravega/test/system/StreamsAndScopesManagementTest.java
> +            StreamConfiguration config = StreamConfiguration.builder().scalingPolicy(ScalingPolicy.fixed(j)).build();
nit: We can add the stream tags right here.

2021-08-13 16:23 UTC, shrids commented
The test successful ran on `test-pravega-continuous-1/1670/`

2021-08-13 16:24 UTC, shrids approved these changes

2021-08-13 16:34 UTC, merged