Issue 6198: (Bugfix) Fix incorrect handling of empty value during listStreams
pravega/pravega pull request #6211
Opened 2021-08-09 04:15 UTC by shrids

Signed-off-by: Sandeep <sandeep.shridhar@emc.com>

**Change log description**  
Fix incorrect handling of empty value during listStreams

**Purpose of the change**  
Fixes #6198 

**What the code does**  
The code fixes the following
* Due to the incorrect isEmptyRecord condition an empty value is being written into the KVT.  This caused the EOFException while attempting to read from this empty record.  
* Improve the robustness of check for last tag index chunk.

**How to verify it**  
The system tests should pass reliably.

2021-08-10 14:31 UTC, andreipaduroiu requested changes
Please add some unit tests for this change.

2021-08-11 10:06 UTC, shrids commented
System test run test-pravega-continuous-1/1661...1663 are succesful with this change set.

2021-08-12 05:10 UTC, shshashwat approved these changes

2021-08-13 08:37 UTC, pbelgundi approved these changes
LGTM

2021-08-13 08:39 UTC, merged