Issue 6223: SLTS - Enable loading third party storages.
pravega/pravega pull request #6231
Opened 2021-08-17 19:11 UTC by sachin-j-joshi

Signed-off-by: Sachin Joshi <sachin.joshi@emc.com>

**Change log description**  
SLTS - Enable loading third party storages.

**Purpose of the change**  
Fixes #6230 

**What the code does**  
- The storageImplementation field in ServiceConfig is a strongly typed enum.
- This is unintentional and prevents loading of third party.
- The field should be a string field/property

**How to verify it**  
All tests should pass

2021-08-18 06:43 UTC, eolivelli requested changes
The patch makes sense to me.

We will have to add some minimal test in order to see it bootstrapping some non system LTS implementation.

I will try to run my custom implementation

2021-08-18 06:44 UTC, eolivelli commented
One question:
where do I put the jars for the LTS implementation ?

2021-08-18 14:27 UTC, sachin-j-joshi commented
The storage implementations are loaded using `ServiceLoader` (https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html)

As long as implementation jar is on the class path it should work.

In fact, there is nothing special about existing bindings other than they are part of the same repo and when we create docker image it puts bindings jar in same directory. But otherwise they use the same mechanism to load.

(The mechanism to load storage factory was already implemented in 0.8 timeframe however this specific bug in config parsing prevented passing arbitrary value to loader.)

Here are the steps to follow. 
**Step 1:**  Add resource file to indicate the class that implements Storage Factory creator
Example - https://github.com/pravega/pravega/blob/master/bindings/src/main/resources/META-INF/services/io.pravega.segmentstore.storage.StorageFactoryCreator

**Step 2:** Implement the StorageFactoryCreator that creates the factory for storage instances
Example  -https://github.com/pravega/pravega/blob/master/bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorageFactoryCreator.java

**Step 3:** Implement factory 
https://github.com/pravega/pravega/blob/master/bindings/src/main/java/io/pravega/storage/filesystem/FileSystemSimpleStorageFactory.java
Add custom configuration.
https://github.com/pravega/pravega/blob/master/bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorageConfig.java


(https://github.com/pravega/pravega/blob/master/bindings/src/main/java/io/pravega/storage/filesystem/FileSystemChunkStorage.java is where ChunkStorage is implemented.)

2021-08-18 15:34 UTC, eolivelli requested changes
Lgtm

So there is no need for additional testing.

2021-08-18 15:34 UTC, eolivelli approved these changes

2021-08-18 16:22 UTC, andreipaduroiu reviewed
This looks OK to me, but how is a user to know how to load an external implementation.

At least one example, even if in a comment, on how to do that and what to pass into this config value would be great. I suggest we write this in the `StorageConfig` class (where we defined this property) and in `config.properties` where we list this property.

2021-08-18 16:22 UTC, andreipaduroiu requested changes
.

2021-08-19 08:24 UTC, eolivelli commented
> At least one example, even if in a comment, on how to do that and what to pass into this config value would be great. I suggest we write this in the `StorageConfig` class (where we defined this property) and in `config.properties` where we list this property.

I second this. good idea @andreipaduroiu

2021-08-19 17:07 UTC, sachin-j-joshi commented
Updated comments - https://github.com/pravega/pravega/pull/6231/commits/9f0d53b6a430d24cdc1d3fa943eea9a1bbdd971b

2021-08-19 17:08 UTC, eolivelli commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorage.java
> + *          File contains name of the class implementing {@link io.pravega.segmentstore.storage.StorageFactoryCreator}.</li>
typo: "File contains name" -> "That file contains the name"

2021-08-23 07:56 UTC, eolivelli commented
@andreipaduroiu can you please take another look ?

cc @diegosalvi you are interested in this patch as well

2021-08-23 15:04 UTC, andreipaduroiu approved these changes

2021-08-23 15:05 UTC, merged