Issue 5889: Make documentation compatible with Docusaurus
pravega/pravega pull request #6308
Opened 2021-09-20 05:22 UTC by Tristan1900

**Change log description**  
Make documentation compatible with Docusaurus

**Purpose of the change**  
Fix #5889 

**What the code does**  
Add sidebar.js
Add doc header for every file
Escape special characters in restAPI.md, add new line after html anchor.
Add pravega-write-read-methods.md

**How to verify it**

2021-09-21 00:06 UTC, claudiofahey approved these changes

2021-09-21 19:23 UTC, derekm commented on documentation/src/docs/pravega-write-read-methods.md
> +Method                                                                                | Write | Transactional Write | Read | Special Features | Notes
We could add:

**Debezium**
https://debezium.io/documentation/reference/operations/debezium-server.html#_pravega
Write: Yes
Transactional Write: Yes
Read: No

2021-09-21 19:25 UTC, derekm commented on documentation/src/docs/pravega-write-read-methods.md
> +[Akka](https://doc.akka.io/docs/alpakka/current/pravega.html)                         | Yes   | No                  | Yes  |                  |
Special Features: KVT

2021-09-21 19:27 UTC, derekm commented on documentation/src/docs/pravega-write-read-methods.md
> +Method                                                                                | Write | Transactional Write | Read | Special Features | Notes
*ZIO*
https://github.com/cheleb/zio-pravega
Write: Yes
Transactional Write: No
Read: Yes

2021-09-21 19:44 UTC, derekm commented on documentation/src/docs/pravega-write-read-methods.md
> +[Apache Flink](../flink-connectors/overview.md)                                       | Yes   | Yes                 | Yes  | EO               |
We need to bring back submodule docs so these "../{flink,spark}-connectors/" links work...

2021-09-21 19:46 UTC, derekm commented on documentation/src/docs/pravega-write-read-methods.md
> +## Pravega Search
This whole section and its listing can be disabled on the open-source side.

2021-09-21 20:26 UTC, derekm requested changes
Can we include rendering the open-source docs from: https://github.com/pravega/docs as within the scope of this PR?

Can we look into porting the mkdocs theme to Docusaurus?
https://github.com/pravega/pravega/tree/master/documentation/src/custom_theme
https://pravega.io/docs/nightly/

We need to replace `./gradlew mkdocsBuild` in build.gradle with a Docusaurus equivalent.

2021-09-21 20:26 UTC, derekm commented on documentation/src/docs/pravega-write-read-methods.md
> +[Apache Flink](../flink-connectors/overview.md)                                       | Yes   | Yes                 | Yes  | EO               |
Can we get these docs to render from here: https://github.com/pravega/docs such that these links work?

2021-09-22 19:33 UTC, derekm approved these changes
I just noticed this is requesting merge into a `docusaurus` branch in the Pravega repo.

With Wenqi leaving us, I guess we can accept this more or less as-is, and reopen the PR under the new branch.

I'm looking at removing mkdocs from the build and introducing new docusaurus commands using gradle npm plugins.

2021-09-22 21:21 UTC, merged