Issue 5536 : LTS - Validate config values
pravega/pravega pull request #6496
Opened 2021-12-16 16:33 UTC by AJadhav29

Signed-off-by: Aditi Jadhav  <Aditi.Jadhav@dell.com>

**Change log description**  
Issue 5536 : LTS - Validate config values 

**Purpose of the change**  
Fixes #5539 

**What the code does**  
Validates the config values 

**How to verify it**  
All tests should pass

2021-12-16 20:54 UTC, sachin-j-joshi requested changes
- Please comments as discussed.
- Please pull master to your branch.
- Need to fix DCO

2021-12-16 20:54 UTC, sachin-j-joshi commented on segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
> +    private void testValueThrowsException(String name, String value) {
Please add comment.

2021-12-16 20:54 UTC, sachin-j-joshi commented on segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
> +    private void testNonFailingValue(String name, String value) {
Please add comment.

2021-12-17 15:36 UTC, AJadhav29 commented on segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
> +    private void testValueThrowsException(String name, String value) {
Added comments

2021-12-17 15:37 UTC, AJadhav29 commented on segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfigTests.java
> +    private void testNonFailingValue(String name, String value) {
Fixed

2021-12-17 15:49 UTC, sachin-j-joshi approved these changes
LGTM

2021-12-17 16:11 UTC, merged