Issue 5637: Improved Constructors of StreamManagerImpl and added a unit Test.
pravega/pravega pull request #6532
Opened 2022-01-19 10:26 UTC by a6dulaleem

Signed-off-by: a6dulaleem <abdul.aleem1@dell.com>

**Change log description**  
Improved the constructors of streamManagerImpl. And added new test case in the streamManagerImplTest for connection pool config testing.

**Purpose of the change**  
Fixing #5637

**What the code does**  
Its merging two constructor without losing backward compatibility. In StreamManagerImplTest adding new unit test case.
and also made visble to connectionPool instance for testing

2022-01-20 05:59 UTC, a6dulaleem commented
Please review @tkaitchuck @SrishT @pbelgundi

2022-01-20 21:04 UTC, tkaitchuck requested changes

2022-01-20 21:04 UTC, tkaitchuck commented on client/src/main/java/io/pravega/client/admin/impl/StreamManagerImpl.java
> -    @VisibleForTesting
This method is only used for tests, so this annotation should remain.

2022-01-21 09:24 UTC, a6dulaleem commented on client/src/main/java/io/pravega/client/admin/impl/StreamManagerImpl.java
> +    protected StreamManagerImpl(ClientConfig clientConfig, ControllerImplConfig controllerConfig, Controller controller,
yeah will do that.

2022-01-24 20:03 UTC, tkaitchuck approved these changes

2022-01-24 20:29 UTC, merged