Issue 4097: Serialization Framework for Synchronizer Config
pravega/pravega pull request #6542
Opened 2022-01-21 19:30 UTC by SrishT

Signed-off-by: SrishT <Srishti.Thakkar@emc.com>

**Change log description**  

**Purpose of the change**  
Fixes #4097 

**What the code does**  

**How to verify it**

2022-01-25 06:25 UTC, SrishT commented on client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
> +            revisionDataOutput.writeBytes(cs.decode(object.eventWriterConfig.toBytes()).toString());
done

2022-01-25 06:25 UTC, SrishT commented on client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
> +            revisionDataInput.readFully(b);
done

2022-01-25 20:29 UTC, tkaitchuck requested changes

2022-01-25 20:29 UTC, tkaitchuck commented on client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
> +            revisionDataOutput.writeArray(object.eventWriterConfig.toBytes().array());
You need to provide arrayOffset and length as it is legal for a byteBuffer's array to have more data in in that just the buffer. (And this as calling code should not depend on anything about the implementation of eventWriter's toBytes method that is not in the signature)

2022-01-25 20:29 UTC, tkaitchuck commented on client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
> +    private static final long serialVersionUID = 3L;
This isn't quite enough to get Java serialization to use our serialization. We have to override it's methods, by implementing a `writeReplace()` and a `readResolve()` method on a "SerializedFrom". Take a look at how this is done at the bottom of `StreamCutImpl` (Which also does it with byte arrays so you can basically copy and paste that code). Or `SegmentImpl` or `StreamImpl` (which do the same thing but with strings)

2022-01-25 20:29 UTC, tkaitchuck commented on client/src/main/java/io/pravega/client/stream/EventWriterConfig.java
> +    private static final long serialVersionUID = 2L;
Same here

2022-01-27 23:52 UTC, tkaitchuck commented on client/src/main/java/io/pravega/client/state/SynchronizerConfig.java
> +            builder.eventWriterConfig.fromBytes(ByteBuffer.wrap(revisionDataInput.readArray()));
This line here is the problem. `fromBytes` is a static method that returns a new event writer config. Here it should call the static method and then set the resulting EventWriterConfig on the builder. Right now it is just throwing it away.

2022-01-28 22:18 UTC, tkaitchuck approved these changes
Looks good.
It looks like to make code cov happy you'll need to have a test for the Java serialization.

2022-02-01 16:48 UTC, tkaitchuck approved these changes

2022-02-01 16:50 UTC, merged