Issue 6600: LTS - Ability to simulate slow LTS
pravega/pravega pull request #6601
Opened 2022-02-21 01:32 UTC by AJadhav29

**Change log description**  
LTS -  Introduce delays and time out for testing.

**Purpose of the change**  
Fixes #6600

**What the code does**  
The code adds new config settings to ChunkedSegmentStorageConfig 
- inject.delay.enbale type boolean
- inject.delay.mean type int
- inject.delay.stddev type int
- StorageLoader should create ChunkedSegmentStorageConfig (similar to line 44)
- Depending on whether inject.delay.enbale is true and inject.storage is true, the StorageLoader::load returns wrapped instance.

Implements FlakyStorageWrapper class implements Storage interface and forwards the calls to wrapped storage,
- However it introduces delays and timeouts as specified in config/parameters above
- FlakyStorageWrapper constructor takes 2 parameters int meanDelay , int stdDeviation
- Don't use Thread.sleep , instead use Futures::delayedFuture passing excecutor and delay. Use CompletableFuture::composeAsync appropriately. 
- Generate delay value using = mean + Random::nextGaussian() * stddev

**How to verify it**  
All the tests should pass

2022-02-21 15:34 UTC, sachin-j-joshi requested changes
I have requested a few minor changes.
Looks good otherwise

2022-02-21 15:34 UTC, sachin-j-joshi commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/SlowStorage.java
> +    final Storage inner;
make  `final protected` for these 3 fields

2022-02-22 00:10 UTC, sachin-j-joshi approved these changes
LGTM

2022-02-23 04:49 UTC, sachin-j-joshi commented
@AJadhav29 Please update the PR description to reflect current design/changes.

2022-02-23 11:14 UTC, RaulGracia requested changes
Thanks, this is useful for our tests from now on. However, I liked more an approach similar to the original description of the PR. The current approach is too simplistic and this limits our testing capabilities:  that is, having a fixed delay will limit us to see whether the system can recover automatically when LTS becomes working properly again (with the current approach, we would need to change the configuration of the fixed delay to 0 and restart all instances).

I suggest the following:
- Add another configuration property that is something similar to `storageextra.slow.delaytype`, so we can use different types of delays (or delay generators).
- At the moment, we could have 2 simple ones: "fixed", which is the one implemented and always generates the same delay (it can be configured via something like `storageextra.slow.fixeddelay.latency.ms`). Then, a "sinusoidal" delay, which induces delays from 0 up to `storageextra.slow.sinusoidal.latency.ms` increasingly up to a period of time `storageextra.slow.sinusoidal.period.ms`, and then goes progressively down to 0 again. This can be easily generated by using `Math.sin()` function based on the time period defined, so we generate "waves" of lower and higher latency of LTS.

The previous suggestion is important because of 3 reasons: i) We need a way to really test that PR https://github.com/pravega/pravega/pull/6597 works, and one of the main aspects to tests is not just it can throttle when it is needed, but also that it can stop throttling when LTS works well again. ii) In general, we need to test that Pravega is self-healing after some period of LTS being unavailable. This "sinusoidal" delay generator is way to achieve this automatically, for instance during our longevity runs. iii) This can help us to measure the max time Pravega can tolerate LTS being slow (by progressively increasing `storageextra.slow.fixeddelay.latency.ms`), if there is actually a max time for that.

2022-03-02 21:42 UTC, sachin-j-joshi requested changes

2022-03-02 21:42 UTC, sachin-j-joshi commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/noop/StorageExtraConfig.java
> +    public static final Property<String> STORAGE_SLOW_MODE_DISTRIBUTION_TYPE = Property.named("slow.type", "Normal");
Please add property public static final Property<Integer> STORAGE_SLOW_MODE_LATENCY_CYCLE_TIME = Property.named("slow.latency.cycle.ms", 300000); // 5 minutes

2022-03-02 21:42 UTC, sachin-j-joshi commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/noop/StorageExtraConfig.java
> +    private final int slowModeLatencyStdDevMillis;
please add 
```
@Getter
    private final int slowModeLatencyCycleTimeMillis;
```

and initialize it in constructor

2022-03-02 21:42 UTC, sachin-j-joshi commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/SlowDelaySuppliers.java
> +            return new SinusoidalDelaySupplier(config.getSlowModeLatencyMeanMillis(), 10);
please use `config.getSlowModeLatencyCycleTimeMillis()` here

2022-03-02 21:50 UTC, sachin-j-joshi requested changes

2022-03-02 21:50 UTC, sachin-j-joshi commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/SlowDelaySuppliers.java
> +    static Supplier<Duration> getDurationSupplier(StorageExtraConfig config) {
Missing comment

2022-03-02 21:50 UTC, sachin-j-joshi commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/SlowDelaySuppliers.java
> +        public long calculateValue(Supplier<Double> randomSupplier) {
may be public is not needed here.

2022-03-02 21:50 UTC, sachin-j-joshi commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/SlowDelaySuppliers.java
> +        public long calculateValue(Supplier<Double> randomSupplier) {
missing comment

2022-03-02 21:50 UTC, sachin-j-joshi commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/SlowDelaySuppliers.java
> +        long calculateValue(long currentTime, long startTime, long cycleTime) {
missing comment

2022-03-02 21:50 UTC, sachin-j-joshi commented on segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/mocks/SlowStorageTests.java
> +    public static class SlowRollingTests extends RollingStorageTests {
missing comment

2022-03-02 21:50 UTC, sachin-j-joshi commented on segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/noop/StorageExtraConfigTest.java
> +        builder.with(Property.named("slow.latency.ms"), 500);
I don't think the property name here correct.
It should be `storageextra.slow.latency.mean.ms`
also please value other than default like 42

2022-03-03 00:43 UTC, sachin-j-joshi commented on segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/noop/StorageExtraConfigTest.java
> +        builder.with(Property.named("storageextra.slow.latency.mean.ms"), 42);
`slow.latency.mean.ms`

2022-03-03 00:44 UTC, sachin-j-joshi commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/noop/StorageExtraConfig.java
> +    public static final Property<Integer> STORAGE_SLOW_MODE_LATENCY_MEAN = Property.named("slow.latency.mean.ms", 42);
please keep it 500

2022-03-03 19:51 UTC, sachin-j-joshi approved these changes
LGTM

2022-03-07 15:42 UTC, AJadhav29 commented
> @sachin-j-joshi the change for adding what I mentioned is minimal and this can enable us to start testing directly. I think it is perfectly doable in this PR just to add the property to select the delay generator and add 2 (fixed and sinusoidal ones). For more complex delay generators, I agree that we can add them later, but let's not delay what we need now for doing proper tests of scenarios where LTS is not operating correctly.
 @RaulGracia I have tried making the changes by adding 2 delay generators- fixed and sinusoidal, as suggested. Please have a look at it and let me know if any further changes or modifications are required.

2022-03-07 15:43 UTC, AJadhav29 commented
@RaulGracia I have tried making the changes by adding 2 delay generators- fixed and sinusoidal, as suggested. Please have a look at it and let me know if any further changes or modifications are required.

2022-03-07 18:24 UTC, RaulGracia approved these changes
Just one minor comment, once you address it we can merge it.

2022-03-07 23:17 UTC, AJadhav29 commented on segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/mocks/SlowDelaySuppliers.java
> +        if (config.getDistributionType().equals("Fixed")) {
@sachin-j-joshi @RaulGracia I have made the changes as suggested by using enumerates for the type of distribution for LTS. It looks good now to me. Please review it and let me know if any further changes are required.

2022-03-07 23:21 UTC, AJadhav29 commented
@sachin-j-joshi @RaulGracia Please have a look at the changes made. I have added enumerate for distribution type of the delay for LTS. Let me know if any further changes are required.

2022-03-07 23:46 UTC, sachin-j-joshi commented
Nice work! 
Just a small change please rename StorageDistributionType to StorageDelayDistributionType.

2022-03-08 15:06 UTC, sachin-j-joshi commented
This change is ready merge 


Except for unrelated flaky test #6626  has started failing constantly since last few days.

2022-03-09 17:42 UTC, merged