Issue 6609: Bump up versions of dependencies
pravega/pravega pull request #6610
Opened 2022-02-25 05:13 UTC by kotlasaicharanreddy

Signed-off-by: root <kotlasaicharan@yahoo.com>

**Change log description**  
(2-3 concise points about the changes in this PR. When committing this PR, the committer is expected to copy the content of this section to the merge description box)

**Purpose of the change**  
Fixes #6609

**What the code does**  
(Detailed description of the code changes)

**How to verify it**  
(Optional: steps to verify that the changes are effective)

2022-03-07 18:12 UTC, derekm approved these changes
Changes look good.

It took 5 attempts to get Segment Store Unit Tests to pass. Has an upgrade affected performance such that these tests are now more stubborn? Or are other builds seeing stubborn Segment Store Unit Tests presently? re: @sachin-j-joshi

2022-03-07 18:15 UTC, sachin-j-joshi commented
In general the upgrade should not affect. 
However are there any specific tests that keep failing repeatedly? 
I have observed that testReport is failing intermittently in other builds.

2022-03-07 18:26 UTC, derekm commented
@sachin-j-joshi,
> However are there any specific tests that keep failing repeatedly? I have observed that testReport is failing intermittently in other builds.

Observed failures:

```
2022-03-04T05:54:55.3060743Z io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testAppendWithOffset FAILED
2022-03-04T05:54:55.3061514Z     java.util.concurrent.TimeoutException: Expected value: 0 observed: 1
2022-03-04T05:54:55.3062141Z         at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:76)
2022-03-04T05:54:55.3062839Z         at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:53)
2022-03-04T05:54:55.3063702Z         at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkAppendLeaks(StreamSegmentContainerTests.java:2812)
2022-03-04T05:54:55.3064732Z         at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testAppendWithOffset(StreamSegmentContainerTests.java:1052)
```

```
2022-03-07T17:22:40.1363131Z io.pravega.segmentstore.server.logs.ThrottlerTests > testInterruptedDecreasingDelayMetrics FAILED
2022-03-07T17:22:40.1364076Z     java.lang.AssertionError: Excepted delay to be at least the smallest value. Expected: greater than or equal to 3000. Actual: 0.
2022-03-07T17:22:40.1364795Z         at org.junit.Assert.fail(Assert.java:89)
2022-03-07T17:22:40.1365405Z         at org.junit.Assert.assertTrue(Assert.java:42)
2022-03-07T17:22:40.1366369Z         at io.pravega.test.common.AssertExtensions.assertGreaterThanOrEqual(AssertExtensions.java:426)
2022-03-07T17:22:40.1368097Z         at io.pravega.segmentstore.server.logs.ThrottlerTests.testInterruptedDecreasingDelayMetrics(ThrottlerTests.java:294)
```

```
2022-03-07T17:23:57.8357404Z io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testAppendWithOffset FAILED
2022-03-07T17:23:57.8358628Z     java.util.concurrent.TimeoutException: Expected value: 0 observed: 1
2022-03-07T17:23:57.8359522Z         at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:76)
2022-03-07T17:23:57.8360766Z         at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:53)
2022-03-07T17:23:57.8362077Z         at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkAppendLeaks(StreamSegmentContainerTests.java:2812)
2022-03-07T17:23:57.8363199Z         at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testAppendWithOffset(StreamSegmentContainerTests.java:1052)
```

```
2022-03-07T17:34:56.6530654Z [31mio.pravega.segmentstore.server.host.HDFSIntegrationTest.testEndToEndWithFencingWithChunkedStorage FAILED. Output (Last 300 lines):[0m
...
2022-03-07T17:34:56.7519896Z  > 2022-03-07 17:34:56,331 202122 [Listener at localhost/41985-SendThread(localhost:25342)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x10000080fa10002 for sever localhost/127.0.0.1:25342, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
2022-03-07T17:34:56.7520576Z  > org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x10000080fa10002, likely server has closed socket
2022-03-07T17:34:56.7521103Z  > 	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
2022-03-07T17:34:56.7521624Z  > 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
2022-03-07T17:34:56.7522082Z  > 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
2022-03-07T17:34:56.7522719Z  > 2022-03-07 17:34:56,331 202122 [NIOServerCxnFactory.AcceptThread:localhost/127.0.0.1:25342] INFO  o.a.z.server.NIOServerCnxnFactory - accept thread exitted run method
...
2022-03-07T17:34:56.7535044Z io.pravega.segmentstore.server.host.HDFSIntegrationTest > testEndToEndWithFencingWithChunkedStorage FAILED
2022-03-07T17:34:56.7535723Z     java.util.concurrent.ExecutionException: io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to establish connection to ZooKeeper or BookKeeper.
2022-03-07T17:34:56.7536332Z         at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
2022-03-07T17:34:56.7536808Z         at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
2022-03-07T17:34:56.7537450Z         at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.endToEndProcessWithFencing(StreamSegmentStoreTestBase.java:570)
2022-03-07T17:34:56.7538391Z         at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.testEndToEndWithFencingWithChunkedStorage(StreamSegmentStoreTestBase.java:529)
2022-03-07T17:34:56.7539101Z         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-03-07T17:34:56.7539622Z         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-03-07T17:34:56.7540191Z         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-03-07T17:34:56.7540661Z         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-03-07T17:34:56.7541076Z         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-03-07T17:34:56.7541562Z         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-03-07T17:34:56.7542063Z         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-03-07T17:34:56.7542566Z         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-03-07T17:34:56.7543085Z         at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
2022-03-07T17:34:56.7543601Z         at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
2022-03-07T17:34:56.7544054Z         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-03-07T17:34:56.7544401Z         at java.base/java.lang.Thread.run(Thread.java:829)
2022-03-07T17:34:56.7544581Z 
2022-03-07T17:34:56.7544660Z         Caused by:
2022-03-07T17:34:56.7545077Z         io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to establish connection to ZooKeeper or BookKeeper.
2022-03-07T17:34:56.7545720Z             at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogFactory.initialize(BookKeeperLogFactory.java:123)
2022-03-07T17:34:56.7546333Z             at io.pravega.segmentstore.server.store.ServiceBuilder.initialize(ServiceBuilder.java:248)
2022-03-07T17:34:56.7546960Z             at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase.createBuilder(StreamSegmentStoreTestBase.java:596)
2022-03-07T17:34:56.7547676Z             at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase$FencingTestContext.lambda$createNewInstance$2(StreamSegmentStoreTestBase.java:1222)
2022-03-07T17:34:56.7548233Z             at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:182)
2022-03-07T17:34:56.7548805Z             at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase$FencingTestContext.createNewInstance(StreamSegmentStoreTestBase.java:1219)
2022-03-07T17:34:56.7549604Z             at io.pravega.segmentstore.server.store.StreamSegmentStoreTestBase$FencingTestContext.lambda$createNewInstanceAsync$1(StreamSegmentStoreTestBase.java:1206)
2022-03-07T17:34:56.7550214Z             at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
2022-03-07T17:34:56.7550699Z             at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
2022-03-07T17:34:56.7551139Z             at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-03-07T17:34:56.7551558 [...]

2022-03-07 18:38 UTC, sachin-j-joshi commented
@RaulGracia FYI

2022-03-07 18:46 UTC, RaulGracia requested changes
Before merging this changes, please check the following:
- Flink/Spark connectors work with these changes.
- Pravega Samples work with these changes.

2022-03-11 10:09 UTC, crazyzhou requested changes
For Flink connector, after I fixed the other issues, this version upgrade works fine against the current Flink connector, the build and all tests can pass.
There are two Pravega commits that causes issues in Flink connector:
- #6559 This forces the scheme in controller uri, so we need to fix this issue in the connector now: https://github.com/pravega/flink-connectors/issues/660 cc. @abhinb next time hope we can get this API change in advance before the Jenkins build alerts.
- #6573 This one put the `final` on some classes, but the Flink connector has a test that requires a mock on `CheckpointImpl` class here. 
https://github.com/pravega/flink-connectors/blob/592c46551ee4b98cf2840143e9759c1661e52ce4/src/test/java/io/pravega/connectors/flink/ReaderCheckpointHookTest.java#L125
The `CheckpointImpl` now does not have a way to mock as a final class, and does not have a public contructor to use. I think we need to fix this. cc. @tkaitchuck 

For Spark connector, I have the following error when tests start:
```
17:55:02,191 ERROR io.pravega.controller.server.ControllerServiceStarter         - Failed trying to start controller services
java.lang.IllegalStateException: Expected the service HealthServiceUpdaterImpl [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:302)
        at com.google.common.util.concurrent.AbstractScheduledService.awaitRunning(AbstractScheduledService.java:412)
        at io.pravega.shared.health.HealthServiceManager.start(HealthServiceManager.java:76)
        at io.pravega.controller.server.ControllerServiceStarter.startUp(ControllerServiceStarter.java:363)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:60)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.AbstractScheduledService$Scheduler.newFixedDelaySchedule(Ljava/time/Duration;Ljava/time/Duration;)Lcom/google/common/util/concurrent/AbstractScheduledService$Scheduler;
        at io.pravega.shared.health.impl.HealthServiceUpdaterImpl.scheduler(HealthServiceUpdaterImpl.java:84)
        at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$2.run(AbstractScheduledService.java:230)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:189)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
```
This looks like caused by a guava upgrade, causing a API mismatch in Health checker service, so Request changes here

2022-03-23 15:18 UTC, kotlasaicharanreddy commented
@crazyzhou Could you please provide the version of Guava and ApacheCurator which are running at runtime? I've checked Guava documentation and there's nothing changed w.r.t to the api pointed in the logs in both guava:28.2-jre and guava:30.0-jre versions.

2022-03-24 03:05 UTC, crazyzhou commented
I have checked the runtime guava version, the problem is actually introduced in the grpc upgrade, which bumps the guava to `30.1-android`, check the tree below:
```
|    +--- io.pravega:pravega-shared-controller-api:0.12.0-3065.8c1f7510f-issue-6609-update-deps
|    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
|    |    +--- io.grpc:grpc-netty-shaded:1.39.0
|    |    |    +--- com.google.guava:guava:30.1-android (*)
|    |    |    +--- com.google.errorprone:error_prone_annotations:2.4.0
|    |    |    +--- io.perfmark:perfmark-api:0.23.0
|    |    |    \--- io.grpc:grpc-core:1.39.0
|    |    |         +--- io.grpc:grpc-api:1.39.0
|    |    |         |    +--- io.grpc:grpc-context:1.39.0
|    |    |         |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |         |    +--- com.google.guava:guava:30.1-android (*)
|    |    |         |    \--- com.google.errorprone:error_prone_annotations:2.4.0
|    |    |         +--- com.google.code.gson:gson:2.8.6
|    |    |         +--- com.google.android:annotations:4.1.1.4
|    |    |         +--- org.codehaus.mojo:animal-sniffer-annotations:1.19
|    |    |         +--- com.google.errorprone:error_prone_annotations:2.4.0
|    |    |         +--- com.google.guava:guava:30.1-android (*)
|    |    |         \--- io.perfmark:perfmark-api:0.23.0
|    |    +--- io.grpc:grpc-protobuf:1.39.0
|    |    |    +--- io.grpc:grpc-api:1.39.0 (*)
|    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |    +--- com.google.protobuf:protobuf-java:3.17.2
|    |    |    +--- com.google.api.grpc:proto-google-common-protos:2.0.1
|    |    |    |    \--- com.google.protobuf:protobuf-java:3.13.0 -> 3.17.2
|    |    |    +--- io.grpc:grpc-protobuf-lite:1.39.0
|    |    |    |    +--- io.grpc:grpc-api:1.39.0 (*)
|    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |    |    \--- com.google.guava:guava:30.1-android (*)
|    |    |    \--- com.google.guava:guava:30.1-android (*)
|    |    +--- io.grpc:grpc-stub:1.39.0
|    |    |    +--- io.grpc:grpc-api:1.39.0 (*)
|    |    |    \--- com.google.guava:guava:30.1-android (*)
|    |    +--- com.google.protobuf:protobuf-java:3.14.0 -> 3.17.2
|    |    +--- io.pravega:pravega-common:0.12.0-3065.8c1f7510f-issue-6609-update-deps (*)
|    |    +--- org.apache.commons:commons-lang3:3.7 -> 3.10
|    |    +--- commons-io:commons-io:2.11.0
|    |    \--- io.grpc:grpc-auth:1.39.0
|    |         +--- io.grpc:grpc-api:1.39.0 (*)
|    |         +--- com.google.auth:google-auth-library-credentials:0.22.2
|    |         \--- com.google.guava:guava:30.1-android (*)
```

Without this version upgrade, the runtime guava version was `30.0-jre` because the highest guava version in the runtime is from bookkeeper:
```
|    |    +--- io.pravega:pravega-segmentstore-storage-impl:0.12.0-3070.b2426ef-SNAPSHOT
|    |    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
|    |    |    +--- io.pravega:pravega-common:0.12.0-3070.b2426ef-SNAPSHOT (*)
|    |    |    +--- io.pravega:pravega-segmentstore-storage:0.12.0-3070.b2426ef-SNAPSHOT (*)
|    |    |    +--- io.pravega:pravega-shared-metrics:0.12.0-3070.b2426ef-SNAPSHOT (*)
|    |    |    +--- org.apache.curator:curator-framework:5.2.0 (*)
|    |    |    \--- org.apache.bookkeeper:bookkeeper-server:4.14.1
|    |    |         +--- org.apache.bookkeeper:bookkeeper-common:4.14.1
|    |    |         |    +--- org.apache.bookkeeper.stats:bookkeeper-stats-api:4.14.1
|    |    |         |    |    +--- commons-configuration:commons-configuration:1.10
|    |    |         |    |    |    +--- commons-lang:commons-lang:2.6
|    |    |         |    |    |    \--- commons-logging:commons-logging:1.1.1 -> 1.2
|    |    |         |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
|    |    |         |    +--- org.apache.bookkeeper:cpu-affinity:4.14.1
|    |    |         |    |    +--- com.google.guava:guava:30.0-jre (*)
|    |    |         |    |    +--- org.apache.commons:commons-lang3:3.6 -> 3.10
|    |    |         |    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
|    |    |         |    |    \--- commons-configuration:commons-configuration:1.10 (*)
|    |    |         |    +--- com.google.guava:guava:30.0-jre (*)
|    |    |         |    +--- io.netty:netty-common:4.1.63.Final -> 4.1.65.Final
|    |    |         |    +--- com.fasterxml.jackson.core:jackson-core:2.11.0 -> 2.12.4 (*)
|    |    |         |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.0 -> 2.12.4 (*)
|    |    |         |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.0 -> 2.12.4 (*)
|    |    |         |    +--- org.jctools:jctools-core:2.1.2
|    |    |         |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
|    |    |         |    \--- commons-configuration:commons-configuration:1.10 (*)
```

So in Spark connector test runtime, this change is actually bumping up guava from `30.0-jre` to `30.1-android`, and I think the problem may be related to the changing from jre into the android version of the `AbstractScheduledService` class.

2022-03-25 09:03 UTC, RaulGracia commented
@kotlasaicharanreddy what is the status with this PR?

2022-03-25 11:18 UTC, crazyzhou approved these changes
After this fix, Spark and Flink connector can work nicely now.

2022-03-25 11:54 UTC, shshashwat commented
@kotlasaicharanreddy , please run the system tests on both TPC and TPC1 and share the result

2022-03-25 12:18 UTC, kotlasaicharanreddy commented
@RaulGracia Pravega-samples, Flink-connector and Spark-connector works fine with these updates.
@shshashwat I've already ran them in the past. Anyways I'll trigger them again.

2022-03-25 12:20 UTC, shshashwat commented
>@shshashwat I've already ran them in the past. Anyways I'll trigger them again.

Would be great if you share the build no here too for reference

2022-03-28 03:26 UTC, kotlasaicharanreddy commented
@shshashwat TPC-4429 and TPC1-2079 are successful system tests for this PR.

2022-03-29 05:13 UTC, shshashwat approved these changes
with the tests performed, it looks good to me

2022-04-01 07:41 UTC, RaulGracia commented
@kotlasaicharanreddy one last question: does this change impact on compatibility? That is, if you instantiate server Pravega 0.0 or 0.11 and a Pravega client with this change (and vice-versa), are things still working fine? Once we know this, I think we are fine with this change.

2022-04-01 07:41 UTC, RaulGracia requested changes
LGTM, just need to acknowledge that this change is not breaking compatibility.

2022-04-01 12:21 UTC, RaulGracia approved these changes

2022-04-01 12:22 UTC, merged