Issue 6674: LTS  - Remove unnecessary pessimistic check in doDelete for S3 and ExtendedS3
pravega/pravega pull request #6675
Opened 2022-04-04 22:27 UTC by sachin-j-joshi

Signed-off-by: Sachin Joshi <sachin.joshi@emc.com>

**Change log description**  
LTS  - Remove unnecessary pessimistic check in doDelete for S3 and ExtendedS3

**Purpose of the change**  
Fixes #6674 

**What the code does**  

- Remove unnecessary pessimistic check in doDelete for S3 and ExtendedS3
- Current tests should already cover the change. https://github.com/pravega/pravega/blob/master/segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkStorageTests.java#L924-L927

**How to verify it**  
All tests should pass.

2022-04-05 16:58 UTC, sachin-j-joshi commented
As expected - in test, no head requests are observed.
![image](https://user-images.githubusercontent.com/44757683/161809204-0ccb764c-e22b-4dd7-9db8-b9017ce10156.png)

2022-04-05 17:35 UTC, RaulGracia requested changes
Looks good, please let us know when system tests are green with these changes.

2022-04-19 07:04 UTC, RaulGracia approved these changes

2022-04-19 07:06 UTC, abhinb approved these changes

2022-04-20 07:57 UTC, merged