Issue 6889: Upgrading adoptOpenJDK and python3 to 3.10.5
pravega/pravega pull request #6890
Opened 2022-09-29 12:30 UTC by kotlasaicharanreddy

**Change log description**  
(2-3 concise points about the changes in this PR. When committing this PR, the committer is expected to copy the content of this section to the merge description box)

**Purpose of the change**  
Fixes #6889

**What the code does**  
(Detailed description of the code changes)

**How to verify it**  
(Optional: steps to verify that the changes are effective)

2022-09-29 18:00 UTC, krishan-Rai approved these changes

2022-10-03 16:16 UTC, RaulGracia approved these changes

2022-10-06 07:21 UTC, shshashwat commented on docker/pravega/Dockerfile
> +    python3=3.10.5-r0 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.16/main \
this need to be changed with `3.10.7`

2022-10-06 07:37 UTC, RaulGracia requested changes
Blocking until fixing Python version.

2022-10-20 08:27 UTC, shshashwat commented
@kotlasaicharanreddy , is this PR still valid? if not then we may want to close this.

2022-10-25 10:48 UTC, RaulGracia commented
Closing, as the Temurin image does not work with glibc.

2022-10-25 10:48 UTC, closed without merging