Issue 6915: Remove AWS and DC/OS deployment guides
pravega/pravega pull request #6918
Opened 2022-10-11 17:56 UTC by derekm

**Change log description**  
Remove AWS Terraform and DC/OS Mesosphere deployment guides

**Purpose of the change**  
Fixes #6915

2022-10-12 09:08 UTC, RaulGracia requested changes
Minor comments. But there is a more relevant topic: if we are deleting this old documentation, what should we do with https://github.com/pravega/pravega/tree/master/deployment/aws package? Should we delete that as well?

2022-10-12 09:08 UTC, RaulGracia commented on documentation/src/docs/deployment/deployment.md
> +- AWS S3, Azure Blob Storage, Google Cloud Storage or a mounted distributed filesystem
Maybe we can leave HDFS as the last option here, right? We still support that.

2022-10-12 19:25 UTC, derekm commented
> if we are deleting this old documentation, what should we do with https://github.com/pravega/pravega/tree/master/deployment/aws package? Should we delete that as well?

I know people do still use Terraform. Even if this is unmaintained, it probably is a good start for someone who wants to pick it back up again and bring it up-to-date, supposing a Terraform user comes to Pravega.

How should we best handle unmaintained but resurrect-able code? Delete and then remember/recover when someone asks? Or let it sit stale until someone notices?

If we choose to let it sit stale, maybe I should move the docs out of the way to deployment/aws and deployment/dcos instead of delete them.

2022-10-17 07:20 UTC, RaulGracia approved these changes

2022-10-17 07:22 UTC, anishakj approved these changes
LGTM

2022-10-17 09:07 UTC, merged