Issue 6934: LTS - Update ECS client to v3.4.5.
pravega/pravega pull request #6935
Opened 2022-10-29 15:43 UTC by sachin-j-joshi

Signed-off-by: Sachin Joshi <sachin.joshi@emc.com>

**Change log description**  
LTS - Update ECS client to v3.4.5. This version fixes smart client issue with retries in presence of unhealthy node.

**Purpose of the change**  
Fixes #6934

**What the code does**  
LTS - Update ECS client to v3.4.5. This version fixes smart client issue with retries in presence of unhealthy node.

**How to verify it**  
Deployment with ECS cluster with some unhealthy nodes should work without problems.

2022-10-31 04:19 UTC, abhinb approved these changes

2022-10-31 09:00 UTC, RaulGracia requested changes
Blocking until the change is tested. Also, if the tests are good, can we do the normal workflow of committing to master and cherry-picking later?

2022-11-01 14:15 UTC, sachin-j-joshi commented
@pavanbhat21 ran tests which passed.

2022-11-01 14:53 UTC, RaulGracia approved these changes

2022-11-01 14:54 UTC, merged