Issue:6945 Lombok breaks compilation with JDK 11:0:17
pravega/pravega pull request #6947
Opened 2022-11-14 11:18 UTC by shshashwat

Signed-off-by: Shashwat Sharma <shashwat_sharma@dell.com>

**Change log description**  
TBD
**Purpose of the change**  
Fixes #6945 

**What the code does**  
TBD

**How to verify it**  
TBD

2022-11-14 15:17 UTC, sachin-j-joshi commented on client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
> +                        ConditionalAppend request = new ConditionalAppend(writerId, appendSequence, expectedOffset,
please add final

2022-11-17 07:36 UTC, eolivelli requested changes

2022-11-17 07:36 UTC, eolivelli commented on segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/AsyncStorageWrapperTests.java
> +            try {
why do we need to change this ?

2022-11-17 08:10 UTC, shshashwat commented on client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java
> +                        ConditionalAppend request = new ConditionalAppend(writerId, appendSequence, expectedOffset,
added at all places

2022-11-17 08:16 UTC, RaulGracia approved these changes

2022-11-17 08:17 UTC, eolivelli approved these changes
+1

2022-11-17 08:18 UTC, merged

2022-11-17 08:18 UTC, eolivelli commented
thank you @RaulGracia for your clarification

2022-11-17 11:27 UTC, shshashwat commented
System test TPC1-4850 succeeded