Issue 7131 Implement Newtonian search for lookup
pravega/pravega pull request #7132
Opened 2023-06-27 04:52 UTC by amit-kumar59

**Change log description**  
In order to support efficient lookups in the index segment we should implement a version of Newtonian search to locate the desired index entry.

**Purpose of the change**  
we want to search over an index segment, which will contain times stamp, offset pairs for, a given segment through the Newtonian Search

**What the code does**  
(Detailed description of the code changes)

**How to verify it**  
(Optional: steps to verify that the changes are effective)

2023-06-27 16:46 UTC, tkaitchuck requested changes

2023-06-27 16:46 UTC, tkaitchuck commented on common/src/main/java/io/pravega/common/util/NewtonianSearch.java
> + * TO-DO.
Add docs

2023-06-27 16:46 UTC, tkaitchuck commented on common/src/main/java/io/pravega/common/util/NewtonianSearch.java
> +    @SuppressWarnings("unchecked")
Add docs

2023-06-27 16:46 UTC, tkaitchuck commented on common/src/main/java/io/pravega/common/util/NewtonianSearch.java
> +public class NewtonianSearch {
Please add this to an appropriate class in common.

2023-06-27 16:46 UTC, tkaitchuck commented on common/src/main/java/io/pravega/common/util/NewtonianSearch.java
> +    @SuppressWarnings("unchecked")
These warnings that are being suppressed are real errors in the code. Please don't ignore lints like this.

2023-06-27 16:46 UTC, tkaitchuck commented on common/src/main/java/io/pravega/common/util/NewtonianSearch.java
> +}
Please add tests which verify:
* Correctness
* Number of lookups compared to binary search
* What happens with invalid input

2023-06-27 16:46 UTC, tkaitchuck commented on common/src/main/java/io/pravega/common/util/NewtonianSearch.java
> +        return -(low + 1);
The semantic of returning a negative value is not clearly expressed in the method signature. As this feature is not needed we should probably omit it.

2023-06-27 16:46 UTC, tkaitchuck commented on common/src/main/java/io/pravega/common/util/NewtonianSearch.java
> +        return -(low + 1);
By returning the index the caller must re-query the valueExtractor or else cache the results on their own. Hence it is better to return both the index and value.

2023-07-24 03:59 UTC, amit-kumar59 commented
Closing this PR as respective changes are incorporated in PR https://github.com/pravega/pravega/pull/7165

2023-07-24 03:59 UTC, closed without merging