Issue 7209: Makes Connect Timeout configurable for system test
pravega/pravega pull request #7211
Opened 2023-08-22 09:11 UTC by a6dulaleem

**Change log description**  
This PR is created to solve the timeout issue happening with failover system test. This PR changes following 

- Make ConnectTimout Configurable for system test
- Set 2 minute timeout for all the system test 

**Purpose of the change**  
fixes #7209 

**What the code does**  
Set Timeout for failover to Two minutes and make it configurable for system test

**How to verify it**  
Run the system test and All test should work fine

2023-08-24 03:13 UTC, tkaitchuck requested changes

2023-08-24 03:13 UTC, tkaitchuck commented on client/src/main/java/io/pravega/client/EventStreamClientFactory.java
> +    <T> EventStreamReader<T> createReader(String readerId, String readerGroup, Serializer<T> s, ReaderConfig config, ClientConfig clientConfig);
This is not needed. The client config is already available to the implementation of this method as a member variable passed in above on line 64.

2023-08-25 03:13 UTC, tkaitchuck approved these changes
Change looks good. I do worry that if the system tests are running into timeouts here, real deployments might hit them under similar circumstances. Do we have an issue to track the investigation into that?

2023-08-25 03:23 UTC, a6dulaleem commented
> Change looks good. I do worry that if the system tests are running into timeouts here, real deployments might hit them under similar circumstances. Do we have an issue to track the investigation into that?

Yeah I created One
https://github.com/pravega/pravega/issues/7221

2023-08-25 04:19 UTC, merged