Issue 7194: Add timeout to SetupAppend and Provide initial delay option to retry
pravega/pravega pull request #7231
Opened 2023-08-30 10:57 UTC by a6dulaleem

**Change log description**  
This PR Basically doing these two thing 

- Adds a timeout (default 30sec) to setting up a connection
- Provide a initial delay option to retry class

**Purpose of the change**  
Fixes #7194 

**What the code does**  
Adds a new timeout as part of the client configuration and triggers a reconnect if a connection cannot be setup within this time.

2023-09-01 04:10 UTC, tkaitchuck commented on client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
> +    SegmentOutputStreamImpl(String segmentName, boolean useConnectionPooling, Controller controller, ConnectionPool connectionPool, UUID writerId, Consumer<Segment> resendToSuccessorsCallback, RetryW
If one of these is for unit tests please annotate it with @VisableForTesting.

2023-09-01 19:41 UTC, tkaitchuck requested changes

2023-09-01 19:41 UTC, tkaitchuck commented on client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java
> +                          // In theory the server should guard against this, but that's not ideal to depend on for client correctness.
This relates to the to 540 above. With this change we should be able to update the code there to fail the connection. Please make that change similar to the reverted PR and have the comments here and there cross reference one other.

2023-09-01 19:41 UTC, tkaitchuck commented on client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java
> +    private static final int WAIT_TILL_RECONNECT_NOT_DONE = 50;
We shouldn't be doing sleep in unit tests. Let's either run with an inline executor and zeroed delayes so we can get determinism or use AssertEventuallyEquals

2023-09-05 15:43 UTC, tkaitchuck approved these changes

2023-09-06 11:36 UTC, abhinb approved these changes

2023-09-06 18:27 UTC, merged