Fix Issue #7433: Update AWS SDK dependency
pravega/pravega pull request #7434
Opened 2024-09-04 15:51 UTC by gfinol

**Change log description**  
Update AWS SDK dependency.

**Purpose of the change**  
Fixes #7433 

**What the code does**  
No code has been changed.

**How to verify it**  
Set up S3 Express as LTS for a Pravega deployment and run the Pravega tester.

2025-02-24 11:59 UTC, RaulGracia approved these changes

2025-02-24 16:04 UTC, RaulGracia requested changes
Blocking until build passes.

2025-03-02 17:32 UTC, gfinol commented
I upgraded to v 2.26.25, which was the original change for this PR (see [cec855c](https://github.com/pravega/pravega/pull/7434/commits/cec855c5fcd055410c826159de14ba3a9032b650)). That change fixes #7433, which was the initial purpose of the PR. 

Now, thanks to #7439, build passes, so I believe that this is ready to merge.

2025-03-02 17:38 UTC, RaulGracia approved these changes

2025-03-02 17:39 UTC, merged